### ISSUE TITLE
Terminal: Incorrect style when setting foreground color in tty.

### ISSUE THREAD

**Issue by Zolyn** [ratatui-org/ratatui#298] opened 2023-07-06 17:08 UTC
## Description

I use the `List` widget to render a list which the selected item has customized style while the others have the default style.

It works as expected in both terminal emulator and tty.

However, when I set the foreground color to white. Things go different in tty.
## To Reproduce

Build from the [Minimal reproduction](https://github.com/Zolyn/ratatui-tty-foreground-repro) and run it in tty.

## Expected behavior

should have the same style in the tty as in the terminal emulator (screenshot below)
![Snipaste_2023-07-07_00-52-27](https://github.com/tui-rs-revival/ratatui/assets/35414841/75b26214-9122-44b6-9604-1c294fcbbcaf)

Reproduced in Arch Linux and Artix Linux (dinit).
## Screenshots

Demo
![demo](https://github.com/tui-rs-revival/ratatui/assets/35414841/e27731f1-9adb-4284-8b20-6bfde6deeefa)

## Environment

- OS: Arch Linux / Artix Linux
- Terminal Emulator: None.
- Font: Terminus
- Crate version: 0.21.0
- Backend: Crossterm

**Comment by joshka** [comment] 2023-07-09 02:43
I'm wondering if this is a Ratatui issue or a crossterm one. Can you please check if the same thing happens for raw crossterm example and also perhaps check termion / termwiz as a backend?

**Comment by joshka** [comment] 2023-07-09 09:27
Thanks for the minimal repro. I thought it might be somewhat related to the issues I'm seeing in #303, but haven't had a chance to view this on a tty yet.

**Comment by mozboz** [comment] 2023-10-09 01:42
I had a look into this bug and I suspect that this is due to the lack of capabilities of the Linux console, not a bug in crossterm or ratatui. I ran the basic crossterm examples in various terminal applications and compared them to the Linux console: the Linux console shows various little glitches, and inabilities to render various features, which generally either work or gracefully fall-back in different desktop terminal applications.

I'm trying to determine if there's a sensible way even for crossterm to be able to detect features of the available terminal and fallback or do a more simple rendering, but this seems like this is way out of scope for ratatui, and ratatui should defer to the supported terminals of the backend chosen - e.g., if you're using crossterm, run the crossterm examples with your chosen console or terminal application to determine if it has the features you want to use. 

References:
1 - Crossterm publishes a list of supported terminal applications here: https://github.com/crossterm-rs/crossterm#tested-terminals . Note that Windows console is specifically called out, but Linux console is not on this list

2 - https://dvdhrm.wordpress.com/2012/08/12/killing-off-config_vt/ - A bit of discussion on how the Linux console works - calling out that it's out of date and only has subset of VT102 features.

Pretty sure this is a 'wont fix', but if the ticket stays open I'll see if I can determine if there are any ways for ratatui/crossterm to gracefully degrade rendering according to features available.

**Closed as not planned** 2023-10-10 15:02 UTC
Labels: Type: Bug
