### ISSUE TITLE
Layout: Documentation for all `Constraint` variants

### ISSUE THREAD

**Issue by hasezoey** [ratatui-org/ratatui#354] opened 2023-07-29 12:16 UTC
## Problem
Currently all variants for `Constraint` dont have documentation, making it difficult to understand the difference between `Max` and `Length` and how they are meant to behave

## Solution
Add rust-doc comments explaining how the variants are meant to be used, like `Length is similar to Max but does ... differently`

it would also be great to have a example for all options (example `layout.rs` is currently missing `Constraint::Max` example)

## Additional context
i am coming from `tui-rs` after having learned that it is not maintained anymore, and just found that `Length` is very similar to `Max` and dont quite understand the difference (if it still had been maintained i would also still have opened the issue there for `Constraint` documentation)

**Comment by joshka** [comment] 2023-07-30 00:03
Welcome to Ratatui. We definitely need more docs and better examples across the board. Happy to take a PR for this.

Answering your main question (what's the difference):
The difference between the Length and Max constraint variants is that Length allocates a fixed amount of space (doing a quick look over the history, it was initially named `Fixed`), while max will grow to fill the space available. So for instance in a 80 character wide terminal, `vec![Length(50), Max(50)]` will work (and allocate [50,30] cols, but `vec![Length(50), Length(50)]` will panic as it cannot allocate 100 columns.

I recently did a small update of the [layout example](https://github.com/ratatui-org/ratatui/tree/main/examples#layout-layoutrs), but it could definitely do with some more detail. Particularly the interaction between various combinations would be good to visually demonstrate (e.g. what happens when you combine multiple constraints). 

The `Layout` code is good enough for basic things, but can be difficult to scale to more complex layouts, so eventually we should probably find some way to use https://crates.io/crates/taffy or some other flex box style approach to layout.

**Comment by hasezoey** [comment] 2023-07-30 13:09
> The difference between the Length and Max constraint variants is that Length allocates a fixed amount of space (doing a quick look over the history, it was initially named Fixed), while max will grow to fill the space available. So for instance in a 80 character wide terminal, vec![Length(50), Max(50)] will work (and allocate [50,30] cols, but vec![Length(50), Length(50)] will panic as it cannot allocate 100 columns.

from my testing (on reasonable terminal sizes), both behave the same (in the final result) and also never panic at any terminal size

Example:
i used the `layout.rs` as a base, ran it once with `Length` and once with `Max` (also had it tested separately in my application, steps:

- started the example
- resized it a bunch around (see tested sizes)
- both gave the same result on reasonable sizes
  result being that both dont go over 4 (vertical) lines if more would be available
  but go below that if not enough is available
  and never panic

tested sizes (width x height, lines as in vertical):
- 106x30: both result in 4 lines max
- 55x16: both still result in 4 lines max
- 55x15: both allocate only 3 lines
- (max) 55x14: allocates only 3 lines
- (length) 55x14 & 55x13: allocates 4 lines
- (max) 55x13 & 55x12: allocates only 2 lines
- (length): 55x12: allocates 2 lines
- (length) 55x11 to 55x9 and below: allocates 4 lines
- (max) 55x11 to 55x10: allocates 1 line
- (max) anything below 55x10: does allocate lines
- (length): 55x8: does not allocate any lines
- (length) 55x7: allocates 3 lines
- (length): 55x6: allocates 2 lines
- (length): 55x5: allocates 1 line
- (length) anything below 55x5: does not allocate lines

terminal: Konsole (KDE) with zsh

**Comment by TieWay59** [comment] 2023-08-01 05:54
I also did some test which shows that `Length` is not working as expected @joshka :

```rust

    #[test]
    fn should_constraint_length_be_fixed()  {
        let rec = Rect::new(0, 0, 0, 30);

        let [blk1, blk2] = *Layout::default()
            .direction(Direction::Vertical)
            .constraints([Constraint::Length(10), Constraint::Max(10)].as_ref())
            //                        ^^^^^^^^^ wish to see 10 for first block
            .split(rec) 
        else {
            return;
        };

        assert_eq!(
            blk1,
            Rect {
                x: 0,
                y: 0,
                width: 0,
                height: 20, // hmmm not? fixed Length?
            }
        );

        assert_eq!(
            blk2,
            Rect {
                x: 0,
                y: 20,
                width: 0,
                height: 10, // max is 10, ok.
            },
        );
    }

    #[should_panic]
    #[test]
    fn should_constraint_length_panic()  {
        let rec = Rect::new(0, 0, 0, 30);

        let [blk1, blk2] = *Layout::default()
            .direction(Direction::Vertical)
            .constraints([Constraint::Length(20), Constraint::Length(20)].as_ref()) 
            .split(rec) 
        else {
            return;
        };

        assert_eq!(
            blk1,
            Rect {
                x: 0,
                y: 0,
                width: 0,
                height: 20,
            }
        );

        assert_eq!(
            blk2,
            Rect {
                x: 0,
                y: 20,
                width: 0,
                height: 10, // ??
            }
        );
    }
```

**Comment by TieWay59** [comment] 2023-08-01 06:51
After a little investigation, I found this issue might be caused by `cassowary::strength` which allows some constraints to break because their strength is `MEDIUM` and it's not high enough to throw panic.


https://github.com/ratatui-org/ratatui/blob/440f62ff5435af9536c55d17707a9bc48dae92cc/src/layout.rs#L307-L318

I tried to replace them all to `REQUIRE`, and the new code can panic as we expect:

```rust
thread 'layout::tests::should_constraint_length_be_fixed' panicked at 'called `Result::unwrap()` on an `Err` value: UnsatisfiableConstraint', src/layout.rs:329:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1076:23
   4: ratatui::layout::split
             at ./src/layout.rs:329:5
   5: ratatui::layout::Layout::split::{{closure}}::{{closure}}
             at ./src/layout.rs:216:36
   6: std::collections::hash::map::Entry<K,V>::or_insert_with
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/collections/hash/map.rs:2558:43
   7: ratatui::layout::Layout::split::{{closure}}
             at ./src/layout.rs:214:13
   8: std::thread::local::LocalKey<T>::try_with
```

But this means users have to consume every space and should not leave blank while `split`. 

I'm not familiar with cassowary algo, I saw @orhun touched some code in this piece. WDUT?

**Comment by TieWay59** [comment] 2023-08-01 06:58
BTW @joshka  : the crate https://github.com/dylanede/cassowary-rs has had no sign of maintenance for 5 years, we really should consider dropping it for a modern algorithm.

**Comment by joshka** [comment] 2023-08-04 09:30
>BTW @joshka : the crate https://github.com/dylanede/cassowary-rs has had no sign of maintenance for 5 years, we really should consider dropping it for a modern algorithm.

yup - definitely :)
There's a Flex layout PR that we pulled over from the tui-rs https://github.com/ratatui-org/ratatui/pull/23
I also recall seeing some commentary from the original author about replacing the layout at some point.
There's also https://crates.io/crates/taffy that could be a good basis for writing a constraint solver approach.

Regarding the approach for documenting this nicely, I'd suggest:
- update the layout example so that it shows a bunch of 12 row high blocks with various combinations of the constraints (e.g. what happens when there's a Min and a Max, a Min and a Length, 2 mins and a max, etc. Use 12 rows as it divides easily into 1,2,3,4,6 which should make it nice to show various layouts.
- Also add some width based examples.
- From the examples, build up some nice ascii art diagrams to add to the docs

Mostly this is going to be an exploration of edge cases by trying things out - my guess is that very few people really fully understand this (I can honestly say I haven't looked at it in depth, so I include myself in that).

**Comment by joshka** [comment] 2023-08-05 13:55
Sorry for some confusion about this. My note about the layout panicking was documenting an observation rather than stating the intended behavior. I don't think this should panic at all.

I noticed a while back that the table example panicked when it went below 80 cols. I was in the process of rewriting the examples to make them nice to display in the examples README consistently and didn't dig much further. The actual failure was in the table `widths()`, not the layout `split()`

The following failed because this isn't satisfied for 79 columns:
```rust
        .widths(&[
            Constraint::Percentage(50),
            Constraint::Length(30),
            Constraint::Min(10),
        ]);
```
I changed the Length to Max in that code and it fixed the issue.

**Comment by hasezoey** [comment] 2023-08-05 14:03
i can now also reproduce a panic, but the following seemingly does not panic:

```rust
Constraint::Percentage(50),
Constraint::Max(30),
Constraint::Length(10),

// or
Constraint::Percentage(50),
Constraint::Min(30),
Constraint::Length(10),
```

given a width of `9`

but if `Length` is in any other position than last, it panics

**Comment by joshka** [comment] 2023-08-05 14:13
My guess is that this should probably never panic and instead just render badly (or perhaps return a result, but that might be more difficult to change the API, and it's not clear what would be the right thing for an app to do with an error)

**Comment by hasezoey** [comment] 2023-08-05 14:20
> or perhaps return a result, but that might be more difficult to change the API, and it's not clear what would be the right thing for an app to do with an error

i am also of that opinion, though that is probably not for this issue, also other things like switching the layout engine would need to be factored in here

just to list some of my opinions:
- it definitely should never panic, because panics should never be catched unless absolutely needed (like FFI boundary) (and a resize may accidentally happen to be lower for a little time, like kde deciding a window should go minimal width out of some reason)
- it should define behavior, instead of being undefined (like currently)
  - define behavior either via some kind of `Constraint::new(Max(1), OnProblem::Panic)`
  - define behavior in one way instead of multiple options (like just return a Result)

*the `OnProblem` enum could look something like
```rust
enum OnProblem {
  Panic, // panic if constraint cannot be fulfilled
  DontRender, // dont render the element (return rect 0,0,0,0)
  Error, // return a result error
}
```

**Comment by joshka** [comment] 2023-08-11 12:41
In https://github.com/ratatui-org/ratatui/pull/393 I updated the layout example to show a bunch of combinations of how constraints interact.

![example](https://vhs.charm.sh/vhs-1ZNoNLNlLtkJXpgg9nCV5e.gif)

**Comment by hasezoey** [comment] 2023-08-12 14:19
re https://github.com/ratatui-org/ratatui/issues/354#issuecomment-1657156443

i have now tried to better understand how cassowary works, and setting `EQ(MEDIUM + 1.0)` basically fixes the weird behavior i have mentioned in that comment for `Length`, only change i have been able to observe (aside from the weird behavior being gone) is that now the `Length` constraint is the one winning while the others are "0" height (in a ~4 height area)

```diff
diff --git a/src/layout.rs b/src/layout.rs
index 8eaa8c5..03241fc 100644
--- a/src/layout.rs
+++ b/src/layout.rs
@@ -327,7 +327,7 @@ fn split(area: Rect, layout: &Layout) -> Rc<[Rect]> {
                 ccs.push(elements[i].y | EQ(REQUIRED) | f64::from(dest_area.y));
                 ccs.push(elements[i].height | EQ(REQUIRED) | f64::from(dest_area.height));
                 ccs.push(match *size {
-                    Constraint::Length(v) => elements[i].width | EQ(MEDIUM) | f64::from(v),
+                    Constraint::Length(v) => elements[i].width | EQ(MEDIUM+1.0) | f64::from(v),
                     Constraint::Percentage(v) => {
                         elements[i].width | EQ(MEDIUM) | (f64::from(v * dest_area.width) / 100.0)
                     }
@@ -356,7 +356,7 @@ fn split(area: Rect, layout: &Layout) -> Rc<[Rect]> {
                 ccs.push(elements[i].x | EQ(REQUIRED) | f64::from(dest_area.x));
                 ccs.push(elements[i].width | EQ(REQUIRED) | f64::from(dest_area.width));
                 ccs.push(match *size {
-                    Constraint::Length(v) => elements[i].height | EQ(MEDIUM) | f64::from(v),
+                    Constraint::Length(v) => elements[i].height | EQ(MEDIUM+1.0) | f64::from(v),
                     Constraint::Percentage(v) => {
                         elements[i].height | EQ(MEDIUM) | (f64::from(v * dest_area.height) / 100.0)
                     }
```

though i am still unsure of if this is a proper solution

**Comment by Valentin271** [comment] 2024-01-14 15:13
I'm closing this because we now have a pretty solid documentation on `Constraint`.

<details><summary>docs.rs for main</summary>
<p>

![image](https://github.com/ratatui-org/ratatui/assets/36198422/ffadb41a-6b83-4941-9924-b15e19c2b1b2)

</p>
</details>

https://github.com/ratatui-org/ratatui/pull/804 adds an example for layout and https://github.com/ratatui-org/ratatui/pull/811 further improves on it.
https://github.com/ratatui-org/ratatui/pull/783 adds an example for constraints.

Feel free to reopen if needed.

**Closed by Valentin271** 2024-01-14 15:13 UTC
Labels: enhancement

**Comment by kdheepak** [comment] 2024-01-14 15:37
There's one more thing I intend to add to the docs: a more detailed discussion about the priorities for the different constraints. I'm planning to do that after this PR is done and merged: https://github.com/ratatui-org/ratatui/pull/788
