### ISSUE TITLE
Ci/Lint: Don't use nightly for formatting

### ISSUE THREAD

**Issue by a-kenji** [ratatui-org/ratatui#295] opened 2023-07-02 10:29 UTC
## Problem

Current formatting requirements might change daily, which has an effect on open pr's.
This seems not very productive.

## Solution
Don't use literal nightly versions of the nightly formatter for lints.
If nightly features are desired provide a way to synchronize the toolchain, for example a specific `rust-toolchain.toml` file, just for the formatter.
That way formatting changes can be coupled with updates of the `rust-toolchain` file itself.

**Comment by joshka** [comment] 2023-07-03 02:26
This has only happened once, and it is pretty quick to fix. (`rustup toolchain install nightly; cargo +nightly fmt; git commit -am 'style: fix fmt issues' ; gh pr create`)
We need to use nightly to enable the group imports and wrap comments features:
```
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 100`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
```

These aren't strictly necessary, but they make it easier to read the comments without having to horizontally scroll, and they make it so that we don't see commits that end up reformatting the imports all the time depending on whatever format the person writing a PR has in their.

Does specifying a specific nightly mean that we need to update that version regularly?

**Comment by joshka** [comment] 2023-07-04 09:35
The issue in https://github.com/tui-rs-revival/ratatui/pull/292 was caused by support for `let-else` statements in rustfmt https://blog.rust-lang.org/2023/07/01/rustfmt-supports-let-else-statements.html

>After updating to one of the toolchains with let-else formatting support, you may notice that `cargo fmt`/`rustfmt` invocations want to "change" the formatting of your let-else statements. However, this isn't actually a "change" in formatting, but instead is simply Rustfmt applying the [let-else formatting rules](https://doc.rust-lang.org/nightly/style-guide/statements.html#else-blocks-let-else-statements) for the very first time.

And linked from there is the [nightly style procedure](https://github.com/rust-lang/style-team/blob/468570a02856a6bbe3994164e1a16a13b56b5cf4/nightly-style-procedure.md) which seems reasonable enough to sit on top of without too much problem:

>Much like breaking nightly feature changes in the Rust compiler, any changes to formatting behavior for nightly syntax should be made cautiously and with thorough consideration to avoid churn. Changes should not be done unnecessarily, and should take into account the feature's adoption and readiness for stabilization.

**Comment by a-kenji** [comment] 2023-07-16 10:15
> This has only happened once, and it is pretty quick to fix. (`rustup toolchain install nightly; cargo +nightly fmt; git commit -am 'style: fix fmt issues' ; gh pr create`) 

While this may seem like an easy fix at first - to me this was a burden due to being resource constrained. Also while I don't expect this to happen regularly - this happened about 5 days after starting to use the nightly formatter, so there were also only 5 opportunities for this to happen.

> Does specifying a specific nightly mean that we need to update that version regularly?

Only if you want to make use of other newer nightly features.

I am fine with closing this issue, if it is not desired but I still would advocate for pinning the version:

- Everyone can use the same version and doesn't need to update daily to get the same behavior
- This can lead to less confusion for new contributors
- Differing behavior can be addressed while updating the version itself


I would also prefer to pin the stable version to avoid similar churn: 
https://github.com/tui-rs-revival/ratatui/pull/310#issuecomment-1635097950 .

**Comment by joshka** [comment] 2023-09-28 07:35
I'm going to close this out, but we can revisit it / reopen it if it does become a more frequent issue.
- There is a makefile target that runs the formatting (`cargo make format`)
- AFAICT, the `rust-toolchain.toml` doesn't support pinning a specific channel to a version, instead it pins a version / channel to your project (i.e. we can't say when using nightly, use this nightly 2023-09-29).

**Closed by joshka** 2023-09-28 07:35 UTC
Labels: enhancement

**Comment by a-kenji** [comment] 2023-09-28 09:40
Sure, no worries.

> AFAICT, the rust-toolchain.toml doesn't support pinning a specific channel to a version, instead it pins a version / channel to your project (i.e. we can't say when using nightly, use this nightly 2023-09-29).

I am not 100% sure what pinning a channel to your project means, but:

```rust
[toolchain]
channel = "nightly-2023-07-01"
components = ["rustfmt"]
targets = [ ]
```

This is a [valid](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) `toolchain.toml` file and it will pick the correct nightly channel.

**Comment by joshka** [comment] 2023-09-28 09:44
We don't want to use nightly generally - only for running rustfmt. That setting would change the compiler for everything we do with the project.
