### ISSUE TITLE
Collapsing borders

### ISSUE THREAD

**Issue by Vinermy** [ratatui-org/ratatui#1316] opened 2024-08-11 10:19 UTC
## Problem
When there are widgets with borders next to each other, both borders are displayed, which leads to wasted space and awkward double borders

## Solution
Add a method on the `Block` struct that makes borders collapsible (a simple true/false value). When two blocks with collapsible borders are placed side-by-side in one `Layout`, draw only one of the borders between them, (`Double` borders have precedence over normal ones) and connect the corners with default box-drawing characters such as `┬` or `╡`

## Additional context
This is how this might look:
```
collapsible_borders: off
╭────────╮╔════════╗
│        │║        ║
│Widget 1│║Widget 2║
│        │║        ║
╰────────╯╚════════╝

collapsible_borders: on
╭────────╦════════╗
│        ║        ║
│Widget 1║Widget 2║
│        ║        ║
╰────────╩════════╝
```
One of the problems is, using wich style should the border between the elements be rendered
This is my solution
1. If borders have different types, determine style based on the type (Double >>> Thick >>> Default >>> Rounded)
2. If borders have the same type, but `border_style` is defined for only one of them, render it with this style
3. Otherwise, take the style from the last element (the lower one for vertical layout, the right one for horizontal)

**Comment by joshka** [comment] 2024-08-11 10:26
Dupe of https://github.com/ratatui-org/ratatui/issues/605 (can you add some more info over there please?). Also see https://ratatui.rs/recipes/layout/collapse-borders/

On the combination, there's a bunch more than just the double / thick / default / rounded. It's likely that instead of defaulting,providing info about the extra corners in the sets is the right thing to do. This way you can have it how you like.

One thing that I'd caution as an aside is that overuse of borders can at times lead to very pedestrian looking apps. Consider if color / background is a good way to convey your information hierarchy.

**Closed** 2024-08-11 10:26 UTC
Labels: Status: Duplicate, Type: Enhancement
