### ISSUE TITLE
Feature request: Expose a reference to the writer in the Backends

### ISSUE THREAD

**Issue by bugnano** [ratatui-org/ratatui#1006] opened 2024-03-30 06:43 UTC
## Problem

Semi-related to #1005 , I'd like to investigate why in the Termion backend doing:

```rust
output.into_raw_mode()?.suspend_raw_mode()?;
```

does not disable raw mode, I was thinking that maybe it's because the Backend is already using io::stdout / io::stderr as its writer, so creating a new variable from io::stderr / io::stdout might be a problem.

If the backend could expose a method like `get_writer_mut() -> &mut W`, I could see if doing

```rust
backend.get_writer_mut().suspend_raw_mode()?;
```

would effectively disable raw mode or not.

Note that I'm also writing an app that switches between alternate screen and raw mode and main screen non-raw mode, and while switching screens works, switching between raw and non-raw mode does not work, so it's not only a bug in the panic handler.

**Comment by joshka** [comment] 2024-04-01 18:36
The writer part is is sort of a dupe of https://github.com/ratatui-org/ratatui/pull/991
And the termion part is covered well enough in the discussion on #1005, so I'm going to close this to avoid bifurcation of the conversaion.

**Closed by joshka** 2024-04-01 18:36 UTC
Labels: enhancement
