### ISSUE TITLE
RGB / 24 bit true color glitching / blinking in macOS terminal.app

### ISSUE THREAD

**Issue by nx10** [ratatui-org/ratatui#475] opened 2023-09-08 16:22 UTC
## Issue Status

macOs terminal does not support TrueColor. This will be documented in the `Color::Rgb` docs (as of PR #477)

Original issue text:

---

## Description

Colors are not working properly in macOS system terminal. I am using crossterm as a backend.

## To Reproduce

Something like this when drawing the buffer

```Rust
let fg = tui::style::Color::Rgb(123, 312, 22); // any color
let bg = tui::style::Color::Rgb(123, 22, 312); // any color
buf.get_mut(0, 0).set_char('▄').set_fg(fg).set_bg(bg);
```

## Expected behavior

Instead of showing the correct colors as expected the whole buffer looks weird and blinks (see video below).

## Screenshots

This is a video of a ratatui application where most of the buffer is constructed like in the example above.

https://github.com/ratatui-org/ratatui/assets/33600480/0a650b5c-ce23-4b7f-be96-b3c60efc8aed

Same terminal with font "SF Mono Regular 11" (System default) so it does not seem to be a font issue

![image](https://github.com/ratatui-org/ratatui/assets/33600480/1ab46313-4ebc-4af1-ab40-c5b52e89c09b)

This is what it looks like in ITerm2 on the same machine (and in every other terminal I tried on linux + windows)

![image](https://github.com/ratatui-org/ratatui/assets/33600480/dd94d645-95d0-4b31-bbc5-95d49c810ecb)

## Environment

- OS: macOS Ventura 13.5 (M2)
- Terminal Emulator: macOS system terminal (Version 2.13 (447))
- Font: Monaco 18 
- Crate version: 0.23.0
- Backend: crossterm

**Comment by joshka** [comment] 2023-09-08 23:27
Do you know if this Is this just the Rgb colors or all colors?
Can you run the colors example and post the output? (I'll add a second view that shows RGB)

As a side note, looking at the image you're displaying (very cool btw), you might be interested in https://crates.io/crates/ratatu-image by @benjajaja

**Comment by joshka** [comment] 2023-09-09 02:33
Using the new colors example from https://github.com/ratatui-org/ratatui/pull/476 I am able to repro this:

<img width="1832" alt="image" src="https://github.com/ratatui-org/ratatui/assets/381361/5c6a7e99-7e25-4937-a7b8-b9eac98742fd">
expected (iterm2):
<img width="1840" alt="image" src="https://github.com/ratatui-org/ratatui/assets/381361/d41da7e6-b82b-4d93-913c-85f882f21301">

**Comment by joshka** [comment] 2023-09-09 03:07
Raised the issue upstream at https://github.com/crossterm-rs/crossterm/issues/819

**Comment by joshka** [comment] 2023-09-09 03:46
The root cause is that Terminal.app doesn't support TrueColor.
https://discussions.apple.com/thread/250459018
https://discussions.apple.com/thread/250636611

Same problem in Termion. Interestingly Termwiz uses an approach that falls back to an ANSI color on non true color enabled terminals, which is neat.

**Comment by joshka** [comment] 2023-09-09 04:18
Because this is something out of our hands (it would require a fix in Terminal.app, the best we can do with this for now is document it - see #477.

Neither Crossterm or Termion expose information on the terminal capabilities to be able to detect if this is a problem, and the Termwiz backend just falls back to the default text color (which is not ideal and perhaps worth fixing if someone wants to do this).

Closing this out as wontfix, but there may be other non-obvious approaches to detecting this that could be worth pursuing if you absolutely need this (i.e. manually checking the terminal capabilities and providing the user with an alternative palette).

**Closed by joshka** 2023-09-09 04:18 UTC
Labels: bug, wontfix

**Comment by nx10** [comment] 2023-09-09 14:54
Thank you so much for the quick response and figuring this out! 

I will likely try to use [terminfo](https://github.com/meh/rust-terminfo) to query capabilities and then either map true color to what is available or abort with a user understandable message.

For context I am building a 3D volumetric viewer for brain imaging / neuroscience. We often want to quickly check what our data looks like on remote clusters and inside containers where we are only connected via a terminal. Ratatui made prototyping this a breeze so thank you and all other conributers a lot!

**Comment by joshka** [comment] 2023-09-09 15:21
If you do want a bit of a head start on this, it's worth taking a look at the termwiz source code. In particular: https://github.com/wez/wezterm/blob/main/termwiz/src/caps/mod.rs

**Comment by nx10** [comment] 2023-09-09 15:39
Seeing the amount of edge cases in this makes me wonder if I should switch to the termwiz backend alltogether until crossterm implements (color) capability querying. But thanks in any case for the pointers!

**Comment by joshka** [comment] 2023-09-09 15:44
Perhaps, but do take note that it hasn't been used anywhere near as much as the other backends, so you're swapping known unknowns for unknown unknowns.
